### ISSUE TITLE
How to get path of selected file?

### ISSUE THREAD

**Issue by MallikarjunH** [helpscout/HSAttachmentPicker#4]
This library is awesome, it helps me a lot. 

The thing is that I want a path of selected file/image/video whatever it is.
In my project, it is asking for path/location of a file. Can you please tell me how to get path?

**Comment by jgritman** [comment]
Glad to hear you find this library useful!

The file path is not exposed through the current implementation, and I don't think we're going to change that. You can fork this library and modify the `upload` delegate method [here](https://github.com/helpscout/HSAttachmentPicker/blob/master/HSAttachmentPicker/Classes/HSAttachmentPicker.h#L11) return an `NSURL` instead of `NSData`.

If you look at these three lines where we call `upload`, it's always pulling the `NSData` from an `NSURL`, so it's easy to swap out that delegate call:
https://github.com/helpscout/HSAttachmentPicker/blob/master/HSAttachmentPicker/Classes/HSAttachmentPicker.m#L133
https://github.com/helpscout/HSAttachmentPicker/blob/master/HSAttachmentPicker/Classes/HSAttachmentPicker.m#L179
https://github.com/helpscout/HSAttachmentPicker/blob/master/HSAttachmentPicker/Classes/HSAttachmentPicker.m#L215
